services:
  moodle:
    container_name: "nett"
    build:
      context: ./moodle
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      MOODLE_DB_TYPE: "mysqli"
      MOODLE_DB_HOST: "mariadb"
      MOODLE_DB_NAME: "moodle"
      MOODLE_DB_USER: "moodle"
      MOODLE_DB_PASSWORD: "moodle"
    depends_on:
      - mariadb
    volumes:
      - ./moodle/code:/var/www/html
      - ./moodle/data:/var/moodledata

  mariadb:
    container_name: "nett_db"
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
      MYSQL_ROOT_PASSWORD: "root_password"
    volumes:
      - ./mariadb/dbdata:/var/lib/mysql
